package org.enumgum.domain.error;

public enum ErrorCode {
  VALIDATION_ERROR,
  EMAIL_NOT_VERIFIED,
  TOKEN_EXPIRED,
  LIMIT_EXCEEDED,
  RATE_LIMITED,
  INTERNAL_SERVER_ERROR,

  //
  AUTHENTICATION_ERROR,
  TOKEN_INVALID,
  INSUFFICIENT_PRIVILEGE,
  ACCESS_DENIED,
  EMAIL_IN_USE,
  RESOURCE_CONFLICT,

  TOKEN_REUSE_DETECTED
  // TOKEN_ALREADY_USED
  // CANNOT_REMOVE_LAST_ADMIN
  // DOWNGRADE_BLOCKED
}
