package org.enumgum.domain.error;

public enum ErrorCode {
  VALIDATION_ERROR,
  EMAIL_NOT_VERIFIED,
  TOKEN_EXPIRED,
  LIMIT_EXCEEDED,
  RATE_LIMITED,
  INTERNAL_SERVER_ERROR,

  //
  AUTHENTICATION_ERROR,
  TOKEN_INVALID,
  INSUFFICIENT_PRIVILEGE,
  ACCESS_DENIED,
  EMAIL_IN_USE,
  RESOURCE_CONFLICT,

  INVALID_REFRESH_TOKEN;
}
