version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: enumgum
      POSTGRES_USER: enumgum
      POSTGRES_PASSWORD: enumgum123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./dev/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgres_data:
