
server:
  port: 8080

spring:
  application:
    name: enum-gum-backend

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#
#  security:
#    userId:
#      password: dummy  # Will be disabled in custom config
#
#management:
#  endpoints.web.exposure.include: health,info,metrics,prometheus
#  endpoint.health.show-details: always
#
#springdoc:
#  api-docs.path: /v3/api-docs
#  swagger-ui.path: /swagger-ui.html
#
#logging:
#  level:
#    org.enumgum: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#
